# Paths
BASEPATH         : '/content/drive/MyDrive/Kaggle_TPS_0822/'
DATAPATH         : '/content/drive/MyDrive/Kaggle_TPS_0822/data/'
SUBMISSIONS      : '/content/drive/MyDrive/Kaggle_TPS_0822/submissions/'
IMAGEPATH        : '/content/drive/MyDrive/Kaggle_TPS_0822/notebooks/images/'

# Pandas init variables
NCOLS            : 100
NROWS            : 100